using Ciphers;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace CaesarCipherTest
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void DecryptionTest()
        {
            CaesarCipher cipher = new CaesarCipher();
            //Assert.AreEqual("АбВгдеЁжЗюЯё", cipher.Decrypt("ДеЖзийЁкЛвГё", 4, "Cyrillic"));
            Assert.AreEqual("What makes every American a typical one is a desire to get a well-paid job that will cover their credit card. A credit card is an indispensable part of life in America. In other words, any American knows that how he or she handles their credit card or cards, either will help them or haunt them for years.In the U.S.getting a card isn’t as hard as it used to be.Some companies now mail applications to high school students, rather than waiting for them to get into college.At their best credit cards allow their owners to reserve hotel rooms, rent cars and finance larger purchases over several months.At their worst, cards allow people with poor money management skills to get into a high - interest debt.For those who are deep in credit card debt, there are some Credit Services agencies that offer anyone in America both online or telephone, and face - to - face counseling.The counselors may propose a debt management plan.The plan includes lower interest payments for clients and setting up a pay off timetable.The agencies’ average client makes about $32, 000 a year and has more than $16, 000 debt in the program.Usually the agencies charge zero up to $30 monthly to manage the debt service plan.Credit Services counselors advise, that if an American gets divorced, he or she may eliminate all joint debts by paying them off or transferring debt into a one-name account.Even in happy marriages, the agency advises that the husband and wife should each have a credit card in their name only to establish separate credit histories.Once debts have been repaid, an American can re-establish his / her good credit by applying for a secured credit card and paying the balance off regularly.A store credit card usually is the next step, followed by applying for a major credit card such as a Visa or MasterCard.(Adapted from \"Indianapolis Woman\")",
                cipher.Decrypt("Alex qeoiw izivc Eqivmger e xctmgep sri mw e hiwmvi xs kix e aipp-temh nsf xlex ampp gsziv xlimv gvihmx gevh. E gvihmx gevh mw er mrhmwtirwefpi tevx sj pmji mr Eqivmge. Mr sxliv asvhw, erc Eqivmger orsaw xlex lsa li sv wli lerhpiw xlimv gvihmx gevh sv gevhw, imxliv ampp lipt xliq sv leyrx xliq jsv cievw.Mr xli Y.W.kixxmrk e gevh mwr’x ew levh ew mx ywih xs fi.Wsqi gsqtermiw rsa qemp ettpmgexmsrw xs lmkl wglssp wxyhirxw, vexliv xler aemxmrk jsv xliq xs kix mrxs gsppiki.Ex xlimv fiwx gvihmx gevhw eppsa xlimv sarivw xs viwivzi lsxip vssqw, virx gevw erh jmrergi pevkiv tyvglewiw sziv wizivep qsrxlw.Ex xlimv asvwx, gevhw eppsa tistpi amxl tssv qsric qerekiqirx womppw xs kix mrxs e lmkl - mrxiviwx hifx.Jsv xlswi als evi hiit mr gvihmx gevh hifx, xlivi evi wsqi Gvihmx Wivzmgiw ekirgmiw xlex sjjiv ercsri mr Eqivmge fsxl srpmri sv xipitlsri, erh jegi - xs - jegi gsyrwipmrk.Xli gsyrwipsvw qec tvstswi e hifx qerekiqirx tper.Xli tper mrgpyhiw psaiv mrxiviwx tecqirxw jsv gpmirxw erh wixxmrk yt e tec sjj xmqixefpi.Xli ekirgmiw’ eziveki gpmirx qeoiw efsyx $32, 000 e ciev erh lew qsvi xler $16, 000 hifx mr xli tvskveq.Ywyeppc xli ekirgmiw glevki divs yt xs $30 qsrxlpc xs qereki xli hifx wivzmgi tper.Gvihmx Wivzmgiw gsyrwipsvw ehzmwi, xlex mj er Eqivmger kixw hmzsvgih, li sv wli qec ipmqmrexi epp nsmrx hifxw fc tecmrk xliq sjj sv xverwjivvmrk hifx mrxs e sri-reqi eggsyrx.Izir mr lettc qevvmekiw, xli ekirgc ehzmwiw xlex xli lywferh erh amji wlsyph iegl lezi e gvihmx gevh mr xlimv reqi srpc xs iwxefpmwl witevexi gvihmx lmwxsvmiw.Srgi hifxw lezi fiir vitemh, er Eqivmger ger vi-iwxefpmwl lmw / liv kssh gvihmx fc ettpcmrk jsv e wigyvih gvihmx gevh erh tecmrk xli fepergi sjj vikypevpc.E wxsvi gvihmx gevh ywyeppc mw xli ribx wxit, jsppsaih fc ettpcmrk jsv e qensv gvihmx gevh wygl ew e Zmwe sv QewxivGevh.(Ehetxih jvsq \"Mrhmeretspmw Asqer\")", 4, "Latin"));
        }

        [TestMethod]
        public void EncryptionTest()
        {
            CaesarCipher cipher = new CaesarCipher();
            //Assert.AreEqual("ДеЖзийЁкЛвГё", cipher.Encrypt("АбВгдеЁжЗюЯё", 4, "Cyrillic"));
            Assert.AreEqual("Alex qeoiw izivc Eqivmger e xctmgep sri mw e hiwmvi xs kix e aipp-temh nsf xlex ampp gsziv xlimv gvihmx gevh. E gvihmx gevh mw er mrhmwtirwefpi tevx sj pmji mr Eqivmge. Mr sxliv asvhw, erc Eqivmger orsaw xlex lsa li sv wli lerhpiw xlimv gvihmx gevh sv gevhw, imxliv ampp lipt xliq sv leyrx xliq jsv cievw.Mr xli Y.W.kixxmrk e gevh mwr’x ew levh ew mx ywih xs fi.Wsqi gsqtermiw rsa qemp ettpmgexmsrw xs lmkl wglssp wxyhirxw, vexliv xler aemxmrk jsv xliq xs kix mrxs gsppiki.Ex xlimv fiwx gvihmx gevhw eppsa xlimv sarivw xs viwivzi lsxip vssqw, virx gevw erh jmrergi pevkiv tyvglewiw sziv wizivep qsrxlw.Ex xlimv asvwx, gevhw eppsa tistpi amxl tssv qsric qerekiqirx womppw xs kix mrxs e lmkl - mrxiviwx hifx.Jsv xlswi als evi hiit mr gvihmx gevh hifx, xlivi evi wsqi Gvihmx Wivzmgiw ekirgmiw xlex sjjiv ercsri mr Eqivmge fsxl srpmri sv xipitlsri, erh jegi - xs - jegi gsyrwipmrk.Xli gsyrwipsvw qec tvstswi e hifx qerekiqirx tper.Xli tper mrgpyhiw psaiv mrxiviwx tecqirxw jsv gpmirxw erh wixxmrk yt e tec sjj xmqixefpi.Xli ekirgmiw’ eziveki gpmirx qeoiw efsyx $32, 000 e ciev erh lew qsvi xler $16, 000 hifx mr xli tvskveq.Ywyeppc xli ekirgmiw glevki divs yt xs $30 qsrxlpc xs qereki xli hifx wivzmgi tper.Gvihmx Wivzmgiw gsyrwipsvw ehzmwi, xlex mj er Eqivmger kixw hmzsvgih, li sv wli qec ipmqmrexi epp nsmrx hifxw fc tecmrk xliq sjj sv xverwjivvmrk hifx mrxs e sri-reqi eggsyrx.Izir mr lettc qevvmekiw, xli ekirgc ehzmwiw xlex xli lywferh erh amji wlsyph iegl lezi e gvihmx gevh mr xlimv reqi srpc xs iwxefpmwl witevexi gvihmx lmwxsvmiw.Srgi hifxw lezi fiir vitemh, er Eqivmger ger vi-iwxefpmwl lmw / liv kssh gvihmx fc ettpcmrk jsv e wigyvih gvihmx gevh erh tecmrk xli fepergi sjj vikypevpc.E wxsvi gvihmx gevh ywyeppc mw xli ribx wxit, jsppsaih fc ettpcmrk jsv e qensv gvihmx gevh wygl ew e Zmwe sv QewxivGevh.(Ehetxih jvsq \"Mrhmeretspmw Asqer\")",
                cipher.Encrypt("What makes every American a typical one is a desire to get a well-paid job that will cover their credit card. A credit card is an indispensable part of life in America. In other words, any American knows that how he or she handles their credit card or cards, either will help them or haunt them for years.In the U.S.getting a card isn’t as hard as it used to be.Some companies now mail applications to high school students, rather than waiting for them to get into college.At their best credit cards allow their owners to reserve hotel rooms, rent cars and finance larger purchases over several months.At their worst, cards allow people with poor money management skills to get into a high - interest debt.For those who are deep in credit card debt, there are some Credit Services agencies that offer anyone in America both online or telephone, and face - to - face counseling.The counselors may propose a debt management plan.The plan includes lower interest payments for clients and setting up a pay off timetable.The agencies’ average client makes about $32, 000 a year and has more than $16, 000 debt in the program.Usually the agencies charge zero up to $30 monthly to manage the debt service plan.Credit Services counselors advise, that if an American gets divorced, he or she may eliminate all joint debts by paying them off or transferring debt into a one-name account.Even in happy marriages, the agency advises that the husband and wife should each have a credit card in their name only to establish separate credit histories.Once debts have been repaid, an American can re-establish his / her good credit by applying for a secured credit card and paying the balance off regularly.A store credit card usually is the next step, followed by applying for a major credit card such as a Visa or MasterCard.(Adapted from \"Indianapolis Woman\")", 4, "Latin"));
        }

        [TestMethod]
        public void HackTest()
        {
            CaesarCipher cipher = new CaesarCipher();
            Assert.AreEqual("«У лукоморья дуб зеленый…» — строки, знакомые каждому с детства. Волшебный мир пушкинских сказок настолько прочно вошел в нашу жизнь, что воспринимается как неотъемлемая часть русской культуры. Поэма «Руслан и Людмила» была закончена Пушкиным в 1820 г., но вступление он дописал в 1825 г. в Михайловском. За его основу поэт взял присказку Арины Родионовны.Вступление Пушкина к поэме продолжает древние традиции русского фольклора.Еще древнерусские гусляры начинали свои сказания с обязательной присказки, не имеющей прямого отношения к сюжету.Эта присказка настраивала слушателей на торжественный лад, создавала особую волшебную атмосферу.Пушкин начинает свою поэму описанием таинственного лукоморья – загадочной местности, где возможны любые чудеса. «Кот ученый» символизирует древнего автора - сказителя, который знает невероятное количество сказок и песен.Лукоморье населено множеством волшебных героев, собравшихся здесь из всех русских сказок.Среди них и второстепенные персонажи(леший, русалка), и «невиданные звери», и пока еще неодушевленная избушка на курьих ножках.Постепенно перед читателем возникают и более значимые герои.Среди неясных видений появляются могучие «тридцать витязей» во главе с Черномором, символизирующие военную силу русского народа.Главные положительные персонажи(королевич, богатырь, царевна) пока еще безымянны.Они являются собирательными образами, которым предстоит воплотиться в конкретной сказке.Завершают волшебную картину основные отрицательные персонажи – Баба - Яга и Кащей Бессмертный, олицетворяющие зло и несправедливость. Пушкин подчеркивает, что весь этот волшебный мир имеет национальные корни.Он непосредственно связан с Россией: «там Русью пахнет!». Все происходящие в этом мире события(подвиги, временные победы злодеев и торжество справедливости) являются отражением реальной жизни.Сказки – это не только выдуманные для развлечения истории.Они по своему освещают действительность и помогают человеку различать добро и зло.В финале присказки Пушкин утверждает, что сам побывал в лукоморье и слушал сказки «кота ученого». Он хочет поделиться одной из таких прекрасных сказок.Интригующее вступление поэта усиливает интерес читателей и нетерпение перед вступлением в волшебный мир народных преданий.",
                cipher.Hack("«Ч пчотртфаг иче лйпйсян…» — хцфтом, лсдотряй одкитрч х ийцхцжд. Жтпьйесян рмф учьомсхомщ ходлто сдхцтпаот уфтыст жтьйп ж сдьч кмлса, ыцт жтхуфмсмрдйцхг одо сйтцюйрпйрдг ыдхца фчххотн очпацчфя. Утбрд «Фчхпдс м Пвирмпд» еяпд лдотсыйсд Учьомсяр ж 1820 з., ст жхцчупйсмй тс итумхдп ж 1825 з. ж Рмщднптжхотр. Лд йзт тхстжч утбц жлгп уфмходлоч Дфмся Фтимтстжся.Жхцчупйсмй Учьомсд о утбрй уфтитпкдйц ифйжсмй цфдимъмм фчххотзт штпаоптфд.Йэй ифйжсйфчххомй зчхпгфя сдымсдпм хжтм ходлдсмг х теглдцйпастн уфмходлом, сй мрйвэйн уфгртзт тцстьйсмг о хвкйцч.Бцд уфмходлод сдхцфдмждпд хпчьдцйпйн сд цтфкйхцжйссян пди, хтлидждпд тхтечв жтпьйесчв дцртхшйфч.Учьомс сдымсдйц хжтв утбрч тумхдсмйр цдмсхцжйсстзт пчотртфаг – лдздитыстн рйхцстхцм, зий жтлрткся пвеяй ычийхд. «Отц чыйсян» хмржтпмлмфчйц ифйжсйзт джцтфд - ходлмцйпг, отцтфян лсдйц сйжйфтгцстй отпмыйхцжт ходлто м уйхйс.Пчотртфай сдхйпйст рсткйхцжтр жтпьйесящ зйфтйж, хтефджьмщхг лийха мл жхйщ фчххомщ ходлто.Хфйим смщ м жцтфтхцйуйссяй уйфхтсдкм(пйьмн, фчхдпод), м «сйжмидссяй лжйфм», м утод йэй сйтичьйжпйссдг млечьод сд очфамщ сткодщ.Утхцйуйсст уйфйи ымцдцйпйр жтлсмодвц м етпйй лсдымряй зйфтм.Хфйим сйгхсящ жмийсмн утгжпгвцхг ртзчымй «цфмиъдца жмцглйн» жт зпджй х Ыйфстртфтр, хмржтпмлмфчвэмй жтйссчв хмпч фчххотзт сдфтид.Зпджсяй утпткмцйпасяй уйфхтсдкм(отфтпйжмы, етздцяфа, ъдфйжсд) утод йэй ейляргсся.Тсм гжпгвцхг хтемфдцйпасярм тефдлдрм, отцтфяр уфйихцтмц жтуптцмцахг ж отсофйцстн ходлой.Лджйфьдвц жтпьйесчв одфцмсч тхстжсяй тцфмъдцйпасяй уйфхтсдкм – Едед - Гзд м Одэйн Ейххрйфцсян, тпмъйцжтфгвэмй лпт м сйхуфджйипмжтхца. Учьомс утиыйфомждйц, ыцт жйха бцтц жтпьйесян рмф мрййц сдъмтсдпасяй отфсм.Тс сйутхфйихцжйсст хжглдс х Фтххмйн: «цдр Фчхав удщсйц!». Жхй уфтмхщтигэмй ж бцтр рмфй хтеяцмг(утижмзм, жфйрйссяй утейия лптиййж м цтфкйхцжт хуфджйипмжтхцм) гжпгвцхг тцфдкйсмйр фйдпастн кмлсм.Ходлом – бцт сй цтпаот жяичрдссяй ипг фдлжпйыйсмг мхцтфмм.Тсм ут хжтйрч тхжйэдвц ийнхцжмцйпастхца м утртздвц ыйптжйоч фдлпмыдца итефт м лпт.Ж шмсдпй уфмходлом Учьомс чцжйфкидйц, ыцт хдр утеяждп ж пчотртфай м хпчьдп ходлом «отцд чыйстзт». Тс щтыйц утийпмцахг тистн мл цдомщ уфйофдхсящ ходлто.Мсцфмзчвэйй жхцчупйсмй утбцд чхмпмждйц мсцйфйх ымцдцйпйн м сйцйфуйсмй уйфйи жхцчупйсмйр ж жтпьйесян рмф сдфтисящ уфйидсмн.",
                "Cyrillic"));
            Assert.AreEqual("What makes every American a typical one is a desire to get a well-paid job that will cover their credit card. A credit card is an indispensable part of life in America. In other words, any American knows that how he or she handles their credit card or cards, either will help them or haunt them for years.In the U.S.getting a card isn’t as hard as it used to be.Some companies now mail applications to high school students, rather than waiting for them to get into college.At their best credit cards allow their owners to reserve hotel rooms, rent cars and finance larger purchases over several months.At their worst, cards allow people with poor money management skills to get into a high - interest debt.For those who are deep in credit card debt, there are some Credit Services agencies that offer anyone in America both online or telephone, and face - to - face counseling.The counselors may propose a debt management plan.The plan includes lower interest payments for clients and setting up a pay off timetable.The agencies’ average client makes about $32, 000 a year and has more than $16, 000 debt in the program.Usually the agencies charge zero up to $30 monthly to manage the debt service plan.Credit Services counselors advise, that if an American gets divorced, he or she may eliminate all joint debts by paying them off or transferring debt into a one-name account.Even in happy marriages, the agency advises that the husband and wife should each have a credit card in their name only to establish separate credit histories.Once debts have been repaid, an American can re-establish his / her good credit by applying for a secured credit card and paying the balance off regularly.A store credit card usually is the next step, followed by applying for a major credit card such as a Visa or MasterCard.(Adapted from \"Indianapolis Woman\")",
                cipher.Hack("Alex qeoiw izivc Eqivmger e xctmgep sri mw e hiwmvi xs kix e aipp-temh nsf xlex ampp gsziv xlimv gvihmx gevh. E gvihmx gevh mw er mrhmwtirwefpi tevx sj pmji mr Eqivmge. Mr sxliv asvhw, erc Eqivmger orsaw xlex lsa li sv wli lerhpiw xlimv gvihmx gevh sv gevhw, imxliv ampp lipt xliq sv leyrx xliq jsv cievw.Mr xli Y.W.kixxmrk e gevh mwr’x ew levh ew mx ywih xs fi.Wsqi gsqtermiw rsa qemp ettpmgexmsrw xs lmkl wglssp wxyhirxw, vexliv xler aemxmrk jsv xliq xs kix mrxs gsppiki.Ex xlimv fiwx gvihmx gevhw eppsa xlimv sarivw xs viwivzi lsxip vssqw, virx gevw erh jmrergi pevkiv tyvglewiw sziv wizivep qsrxlw.Ex xlimv asvwx, gevhw eppsa tistpi amxl tssv qsric qerekiqirx womppw xs kix mrxs e lmkl - mrxiviwx hifx.Jsv xlswi als evi hiit mr gvihmx gevh hifx, xlivi evi wsqi Gvihmx Wivzmgiw ekirgmiw xlex sjjiv ercsri mr Eqivmge fsxl srpmri sv xipitlsri, erh jegi - xs - jegi gsyrwipmrk.Xli gsyrwipsvw qec tvstswi e hifx qerekiqirx tper.Xli tper mrgpyhiw psaiv mrxiviwx tecqirxw jsv gpmirxw erh wixxmrk yt e tec sjj xmqixefpi.Xli ekirgmiw’ eziveki gpmirx qeoiw efsyx $32, 000 e ciev erh lew qsvi xler $16, 000 hifx mr xli tvskveq.Ywyeppc xli ekirgmiw glevki divs yt xs $30 qsrxlpc xs qereki xli hifx wivzmgi tper.Gvihmx Wivzmgiw gsyrwipsvw ehzmwi, xlex mj er Eqivmger kixw hmzsvgih, li sv wli qec ipmqmrexi epp nsmrx hifxw fc tecmrk xliq sjj sv xverwjivvmrk hifx mrxs e sri-reqi eggsyrx.Izir mr lettc qevvmekiw, xli ekirgc ehzmwiw xlex xli lywferh erh amji wlsyph iegl lezi e gvihmx gevh mr xlimv reqi srpc xs iwxefpmwl witevexi gvihmx lmwxsvmiw.Srgi hifxw lezi fiir vitemh, er Eqivmger ger vi-iwxefpmwl lmw / liv kssh gvihmx fc ettpcmrk jsv e wigyvih gvihmx gevh erh tecmrk xli fepergi sjj vikypevpc.E wxsvi gvihmx gevh ywyeppc mw xli ribx wxit, jsppsaih fc ettpcmrk jsv e qensv gvihmx gevh wygl ew e Zmwe sv QewxivGevh.(Ehetxih jvsq \"Mrhmeretspmw Asqer\")", "Latin"));
        }
    }
}
